"""initial_schema

Revision ID: 1e7d53d90f82
Revises: 
Create Date: 2026-09-05 01:04:30.464776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e7d53d90f82'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('section', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shows_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_shows_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shows_section'), ['section'], unique=False)
        batch_op.create_index(batch_op.f('ix_shows_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_shows_title'), ['title'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('publish_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('triggered_by', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('outcome', sa.String(length=50), nullable=False),
    sa.Column('show_count', sa.Integer(), nullable=False),
    sa.Column('episode_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('publish_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_publish_runs_id'), ['id'], unique=False)

    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('show_id', sa.Integer(), nullable=False),
    sa.Column('season_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seasons_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_seasons_show_id'), ['show_id'], unique=False)

    op.create_table('episodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('episode_number', sa.Integer(), nullable=False),
    sa.Column('content_group', sa.String(length=100), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_group', 'language', name='uq_content_group_language')
    )
    with op.batch_alter_table('episodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_episodes_content_group'), ['content_group'], unique=False)
        batch_op.create_index(batch_op.f('ix_episodes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_episodes_season_id'), ['season_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_episodes_status'), ['status'], unique=False)

    op.create_table('artwork',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artwork', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artwork_episode_id'), ['episode_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_artwork_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artwork', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artwork_id'))
        batch_op.drop_index(batch_op.f('ix_artwork_episode_id'))

    op.drop_table('artwork')
    with op.batch_alter_table('episodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_episodes_status'))
        batch_op.drop_index(batch_op.f('ix_episodes_season_id'))
        batch_op.drop_index(batch_op.f('ix_episodes_id'))
        batch_op.drop_index(batch_op.f('ix_episodes_content_group'))

    op.drop_table('episodes')
    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seasons_show_id'))
        batch_op.drop_index(batch_op.f('ix_seasons_id'))

    op.drop_table('seasons')
    with op.batch_alter_table('publish_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_publish_runs_id'))

    op.drop_table('publish_runs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('shows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shows_title'))
        batch_op.drop_index(batch_op.f('ix_shows_status'))
        batch_op.drop_index(batch_op.f('ix_shows_section'))
        batch_op.drop_index(batch_op.f('ix_shows_id'))
        batch_op.drop_index(batch_op.f('ix_shows_category'))

    op.drop_table('shows')
    # ### end Alembic commands ###
